export const GENERATION_NUMBER: Readonly<Record<string, number>> = {
  "generation-i": 1,
  "generation-ii": 2,
  "generation-iii": 3,
  "generation-iv": 4,
  "generation-v": 5,
  "generation-vi": 6,
  "generation-vii": 7,
  "generation-viii": 8,
  "generation-ix": 9,
};

export const VERSION_GROUP_GENERATION: Readonly<Record<string, number>> = {
  "red-blue": 1,
  yellow: 1,
  "red-green-japan": 1,
  "blue-japan": 1,
  "gold-silver": 2,
  crystal: 2,
  "ruby-sapphire": 3,
  emerald: 3,
  "firered-leafgreen": 3,
  colosseum: 3,
  xd: 3,
  "diamond-pearl": 4,
  platinum: 4,
  "heartgold-soulsilver": 4,
  "black-white": 5,
  "black-2-white-2": 5,
  "x-y": 6,
  "omega-ruby-alpha-sapphire": 6,
  "sun-moon": 7,
  "ultra-sun-ultra-moon": 7,
  "lets-go-pikachu-lets-go-eevee": 7,
  "sword-shield": 8,
  "the-isle-of-armor": 8,
  "the-crown-tundra": 8,
  "brilliant-diamond-shining-pearl": 8,
  "legends-arceus": 8,
  "scarlet-violet": 9,
  "the-teal-mask": 9,
  "the-indigo-disk": 9,
  "legends-za": 9,
  "mega-dimension": 9,
  champions: 9,
};
