/**
 * Abilities referenced by at least one Gen 4 species (non-hidden only).
 *
 * Generated by scripts/extract-pokedex.ts from PokeAPI (https://pokeapi.co/). Do not
 * hand-edit — re-run the generator instead.
 *
 * Values are Gen 4 (HeartGold/SoulSilver) specific: PokeAPI serves present-day values by
 * default, so types/abilities/move stats are resolved from `past_types`/`past_abilities`/
 * `past_values` where Gen 4 differs from today. See the header comment in
 * scripts/extract-pokedex.ts for exactly how.
 */

export interface AbilityDef {
  id: number;
  name: string;
  shortEffect: string;
}

export const abilities: AbilityDef[] = [
  {
    id: 1,
    name: "stench",
    shortEffect: "Has a 10% chance of making target Pokémon flinch with each hit.",
  },
  {
    id: 2,
    name: "drizzle",
    shortEffect: "Summons rain that lasts indefinitely upon entering battle.",
  },
  { id: 3, name: "speed-boost", shortEffect: "Raises Speed one stage after each turn." },
  { id: 4, name: "battle-armor", shortEffect: "Protects against critical hits." },
  {
    id: 5,
    name: "sturdy",
    shortEffect:
      "Prevents being KOed from full HP, leaving 1 HP instead. Protects against the one-hit KO moves regardless of HP.",
  },
  {
    id: 6,
    name: "damp",
    shortEffect:
      "Prevents Self-Destruct, Explosion, and Aftermath from working while the Pokémon is in battle.",
  },
  { id: 7, name: "limber", shortEffect: "Prevents paralysis." },
  {
    id: 8,
    name: "sand-veil",
    shortEffect:
      "Increases evasion to 1.25× during a sandstorm. Protects against sandstorm damage.",
  },
  {
    id: 9,
    name: "static",
    shortEffect: "Has a 30% chance of paralyzing attacking Pokémon on contact.",
  },
  { id: 10, name: "volt-absorb", shortEffect: "Absorbs Electric moves, healing for 1/4 max HP." },
  { id: 11, name: "water-absorb", shortEffect: "Absorbs Water moves, healing for 1/4 max HP." },
  {
    id: 12,
    name: "oblivious",
    shortEffect: "Prevents infatuation and protects against Captivate.",
  },
  {
    id: 13,
    name: "cloud-nine",
    shortEffect: "Negates all effects of weather, but does not prevent the weather itself.",
  },
  { id: 14, name: "compound-eyes", shortEffect: "Increases moves' accuracy to 1.3×." },
  { id: 15, name: "insomnia", shortEffect: "Prevents sleep." },
  {
    id: 16,
    name: "color-change",
    shortEffect: "Changes type to match when hit by a damaging move.",
  },
  { id: 17, name: "immunity", shortEffect: "Prevents poison." },
  {
    id: 18,
    name: "flash-fire",
    shortEffect:
      "Protects against Fire moves. Once one has been blocked, the Pokémon's own Fire moves inflict 1.5× damage until it leaves battle.",
  },
  { id: 19, name: "shield-dust", shortEffect: "Protects against incoming moves' extra effects." },
  { id: 20, name: "own-tempo", shortEffect: "Prevents confusion." },
  {
    id: 21,
    name: "suction-cups",
    shortEffect: "Prevents being forced out of battle by other Pokémon's moves.",
  },
  {
    id: 22,
    name: "intimidate",
    shortEffect: "Lowers opponents' Attack one stage upon entering battle.",
  },
  { id: 23, name: "shadow-tag", shortEffect: "Prevents opponents from fleeing or switching out." },
  {
    id: 24,
    name: "rough-skin",
    shortEffect: "Damages attacking Pokémon for 1/8 their max HP on contact.",
  },
  {
    id: 25,
    name: "wonder-guard",
    shortEffect: "Protects against damaging moves that are not super effective.",
  },
  { id: 26, name: "levitate", shortEffect: "Evades Ground moves." },
  {
    id: 27,
    name: "effect-spore",
    shortEffect:
      "Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pokémon on contact.",
  },
  {
    id: 28,
    name: "synchronize",
    shortEffect:
      "Copies burns, paralysis, and poison received onto the Pokémon that inflicted them.",
  },
  {
    id: 29,
    name: "clear-body",
    shortEffect: "Prevents stats from being lowered by other Pokémon.",
  },
  {
    id: 30,
    name: "natural-cure",
    shortEffect: "Cures any major status ailment upon switching out.",
  },
  {
    id: 31,
    name: "lightning-rod",
    shortEffect:
      "Redirects single-target Electric moves to this Pokémon where possible. Absorbs Electric moves, raising Special Attack one stage.",
  },
  {
    id: 32,
    name: "serene-grace",
    shortEffect: "Doubles the chance of moves' extra effects occurring.",
  },
  { id: 33, name: "swift-swim", shortEffect: "Doubles Speed during rain." },
  { id: 34, name: "chlorophyll", shortEffect: "Doubles Speed during strong sunlight." },
  { id: 35, name: "illuminate", shortEffect: "Doubles the wild encounter rate." },
  { id: 36, name: "trace", shortEffect: "Copies an opponent's ability upon entering battle." },
  { id: 37, name: "huge-power", shortEffect: "Doubles Attack in battle." },
  {
    id: 38,
    name: "poison-point",
    shortEffect: "Has a 30% chance of poisoning attacking Pokémon on contact.",
  },
  { id: 39, name: "inner-focus", shortEffect: "Prevents flinching." },
  { id: 40, name: "magma-armor", shortEffect: "Prevents freezing." },
  { id: 41, name: "water-veil", shortEffect: "Prevents burns." },
  {
    id: 42,
    name: "magnet-pull",
    shortEffect: "Prevents Steel opponents from fleeing or switching out.",
  },
  { id: 43, name: "soundproof", shortEffect: "Protects against sound-based moves." },
  { id: 44, name: "rain-dish", shortEffect: "Heals for 1/16 max HP after each turn during rain." },
  {
    id: 45,
    name: "sand-stream",
    shortEffect: "Summons a sandstorm that lasts indefinitely upon entering battle.",
  },
  {
    id: 46,
    name: "pressure",
    shortEffect: "Increases the PP cost of moves targetting the Pokémon by one.",
  },
  { id: 47, name: "thick-fat", shortEffect: "Halves damage from Fire and Ice moves." },
  { id: 48, name: "early-bird", shortEffect: "Makes sleep pass twice as quickly." },
  {
    id: 49,
    name: "flame-body",
    shortEffect: "Has a 30% chance of burning attacking Pokémon on contact.",
  },
  { id: 50, name: "run-away", shortEffect: "Ensures success fleeing from wild battles." },
  { id: 51, name: "keen-eye", shortEffect: "Prevents accuracy from being lowered." },
  {
    id: 52,
    name: "hyper-cutter",
    shortEffect: "Prevents Attack from being lowered by other Pokémon.",
  },
  {
    id: 53,
    name: "pickup",
    shortEffect:
      "Picks up other Pokémon's used and Flung held items. May also pick up an item after battle.",
  },
  { id: 54, name: "truant", shortEffect: "Skips every second turn." },
  {
    id: 55,
    name: "hustle",
    shortEffect:
      "Strengthens physical moves to inflict 1.5× damage, but decreases their accuracy to 0.8×.",
  },
  {
    id: 56,
    name: "cute-charm",
    shortEffect: "Has a 30% chance of infatuating attacking Pokémon on contact.",
  },
  {
    id: 57,
    name: "plus",
    shortEffect: "Increases Special Attack to 1.5× when a friendly Pokémon has Plus or Minus.",
  },
  {
    id: 58,
    name: "minus",
    shortEffect: "Increases Special Attack to 1.5× when a friendly Pokémon has Plus or Minus.",
  },
  {
    id: 59,
    name: "forecast",
    shortEffect: "Changes Castform's type and form to match the weather.",
  },
  {
    id: 60,
    name: "sticky-hold",
    shortEffect: "Prevents a held item from being removed by other Pokémon.",
  },
  {
    id: 61,
    name: "shed-skin",
    shortEffect: "Has a 33% chance of curing any major status ailment after each turn.",
  },
  { id: 62, name: "guts", shortEffect: "Increases Attack to 1.5× with a major status ailment." },
  {
    id: 63,
    name: "marvel-scale",
    shortEffect: "Increases Defense to 1.5× with a major status ailment.",
  },
  {
    id: 64,
    name: "liquid-ooze",
    shortEffect: "Damages opponents using leeching moves for as much as they would heal.",
  },
  {
    id: 65,
    name: "overgrow",
    shortEffect: "Strengthens Grass moves to inflict 1.5× damage at 1/3 max HP or less.",
  },
  {
    id: 66,
    name: "blaze",
    shortEffect: "Strengthens Fire moves to inflict 1.5× damage at 1/3 max HP or less.",
  },
  {
    id: 67,
    name: "torrent",
    shortEffect: "Strengthens Water moves to inflict 1.5× damage at 1/3 max HP or less.",
  },
  {
    id: 68,
    name: "swarm",
    shortEffect: "Strengthens Bug moves to inflict 1.5× damage at 1/3 max HP or less.",
  },
  { id: 69, name: "rock-head", shortEffect: "Protects against recoil damage." },
  {
    id: 70,
    name: "drought",
    shortEffect: "Summons strong sunlight that lasts indefinitely upon entering battle.",
  },
  {
    id: 71,
    name: "arena-trap",
    shortEffect:
      "Prevents opponents from fleeing or switching out. Eluded by Flying-types and Pokémon in the air.",
  },
  { id: 72, name: "vital-spirit", shortEffect: "Prevents sleep." },
  {
    id: 73,
    name: "white-smoke",
    shortEffect: "Prevents stats from being lowered by other Pokémon.",
  },
  { id: 74, name: "pure-power", shortEffect: "Doubles Attack in battle." },
  { id: 75, name: "shell-armor", shortEffect: "Protects against critical hits." },
  {
    id: 76,
    name: "air-lock",
    shortEffect: "Negates all effects of weather, but does not prevent the weather itself.",
  },
  { id: 77, name: "tangled-feet", shortEffect: "Doubles evasion when confused." },
  { id: 78, name: "motor-drive", shortEffect: "Absorbs Electric moves, raising Speed one stage." },
  {
    id: 79,
    name: "rivalry",
    shortEffect:
      "Increases damage inflicted to 1.25× against Pokémon of the same gender, but decreases damage to 0.75× against the opposite gender.",
  },
  { id: 80, name: "steadfast", shortEffect: "Raises Speed one stage upon flinching." },
  {
    id: 81,
    name: "snow-cloak",
    shortEffect: "Increases evasion to 1.25× during hail. Protects against hail damage.",
  },
  {
    id: 82,
    name: "gluttony",
    shortEffect: "Makes the Pokémon eat any held Berry triggered by low HP below 1/2 its max HP.",
  },
  {
    id: 83,
    name: "anger-point",
    shortEffect: "Raises Attack to the maximum of six stages upon receiving a critical hit.",
  },
  { id: 84, name: "unburden", shortEffect: "Doubles Speed upon using or losing a held item." },
  { id: 85, name: "heatproof", shortEffect: "Halves damage from Fire moves and burns." },
  {
    id: 86,
    name: "simple",
    shortEffect:
      "Doubles the Pokémon's stat modifiers. These doubled modifiers are still capped at -6 or 6 stages.",
  },
  {
    id: 87,
    name: "dry-skin",
    shortEffect:
      "Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain. Increases damage from Fire moves to 1.25×, but absorbs Water moves, healing for 1/4 max HP.",
  },
  {
    id: 88,
    name: "download",
    shortEffect:
      "Raises the attack stat corresponding to the opponents' weaker defense one stage upon entering battle.",
  },
  { id: 89, name: "iron-fist", shortEffect: "Strengthens punch-based moves to 1.2× their power." },
  {
    id: 90,
    name: "poison-heal",
    shortEffect: "Heals for 1/8 max HP after each turn when poisoned in place of damage.",
  },
  {
    id: 91,
    name: "adaptability",
    shortEffect: "Increases the same-type attack bonus from 1.5× to 2×.",
  },
  {
    id: 92,
    name: "skill-link",
    shortEffect: "Extends two-to-five-hit moves and Triple Kick to their full length every time.",
  },
  {
    id: 93,
    name: "hydration",
    shortEffect: "Cures any major status ailment after each turn during rain.",
  },
  {
    id: 94,
    name: "solar-power",
    shortEffect:
      "Increases Special Attack to 1.5× but costs 1/8 max HP after each turn during strong sunlight.",
  },
  {
    id: 95,
    name: "quick-feet",
    shortEffect: "Increases Speed to 1.5× with a major status ailment.",
  },
  { id: 96, name: "normalize", shortEffect: "Makes the Pokémon's moves all act Normal-type." },
  {
    id: 97,
    name: "sniper",
    shortEffect: "Strengthens critical hits to inflict 3× damage rather than 2×.",
  },
  {
    id: 98,
    name: "magic-guard",
    shortEffect: "Protects against damage not directly caused by a move.",
  },
  {
    id: 99,
    name: "no-guard",
    shortEffect: "Ensures all moves used by and against the Pokémon hit.",
  },
  {
    id: 100,
    name: "stall",
    shortEffect: "Makes the Pokémon move last within its move's priority bracket.",
  },
  {
    id: 101,
    name: "technician",
    shortEffect: "Strengthens moves of 60 base power or less to 1.5× their power.",
  },
  {
    id: 102,
    name: "leaf-guard",
    shortEffect: "Protects against major status ailments during strong sunlight.",
  },
  {
    id: 103,
    name: "klutz",
    shortEffect: "Prevents the Pokémon from using its held item in battle.",
  },
  {
    id: 104,
    name: "mold-breaker",
    shortEffect: "Bypasses targets' abilities if they could hinder or prevent a move.",
  },
  { id: 105, name: "super-luck", shortEffect: "Raises moves' critical hit rates one stage." },
  {
    id: 106,
    name: "aftermath",
    shortEffect: "Damages the attacker for 1/4 its max HP when knocked out by a contact move.",
  },
  {
    id: 107,
    name: "anticipation",
    shortEffect:
      "Notifies all trainers upon entering battle if an opponent has a super-effective move, Self-Destruct, Explosion, or a one-hit KO move.",
  },
  {
    id: 108,
    name: "forewarn",
    shortEffect: "Reveals the opponents' strongest move upon entering battle.",
  },
  {
    id: 109,
    name: "unaware",
    shortEffect: "Ignores other Pokémon's stat modifiers for damage and accuracy calculation.",
  },
  {
    id: 110,
    name: "tinted-lens",
    shortEffect: "Doubles damage inflicted with not-very-effective moves.",
  },
  {
    id: 111,
    name: "filter",
    shortEffect: "Decreases damage taken from super-effective moves by 1/4.",
  },
  {
    id: 112,
    name: "slow-start",
    shortEffect: "Halves Attack and Speed for five turns upon entering battle.",
  },
  {
    id: 113,
    name: "scrappy",
    shortEffect: "Lets the Pokémon's Normal and Fighting moves hit Ghost Pokémon.",
  },
  {
    id: 114,
    name: "storm-drain",
    shortEffect:
      "Redirects single-target Water moves to this Pokémon where possible. Absorbs Water moves, raising Special Attack one stage.",
  },
  {
    id: 115,
    name: "ice-body",
    shortEffect: "Heals for 1/16 max HP after each turn during hail. Protects against hail damage.",
  },
  {
    id: 116,
    name: "solid-rock",
    shortEffect: "Decreases damage taken from super-effective moves by 1/4.",
  },
  {
    id: 117,
    name: "snow-warning",
    shortEffect: "Summons hail that lasts indefinitely upon entering battle.",
  },
  { id: 118, name: "honey-gather", shortEffect: "The Pokémon may pick up Honey after battle." },
  { id: 119, name: "frisk", shortEffect: "Reveals an opponent's held item upon entering battle." },
  { id: 120, name: "reckless", shortEffect: "Strengthens recoil moves to 1.2× their power." },
  {
    id: 121,
    name: "multitype",
    shortEffect: "Changes Arceus's type and form to match its held Plate.",
  },
  {
    id: 122,
    name: "flower-gift",
    shortEffect:
      "Increases friendly Pokémon's Attack and Special Defense to 1.5× during strong sunlight.",
  },
  {
    id: 123,
    name: "bad-dreams",
    shortEffect: "Damages sleeping opponents for 1/8 their max HP after each turn.",
  },
  {
    id: 172,
    name: "competitive",
    shortEffect: "Raises Special Attack by two stages upon having any stat lowered.",
  },
  {
    id: 274,
    name: "wind-rider",
    shortEffect:
      "Gives immunity to wind moves, and causes the Pokémon's Attack to increase by one stage when hit by one.",
  },
  { id: 292, name: "sharpness", shortEffect: "Powers up slicing moves." },
];
