/**
 * The 25 natures, hand-written rather than extracted (per CLAUDE.md "Game data": these are
 * static and tiny, and the same 25-nature stat chart has never changed since Gen 3). Not
 * generated by scripts/extract-pokedex.ts.
 *
 * Each nature raises one stat by 10% and lowers a different one by 10%, except the 5 "neutral"
 * natures (Hardy, Docile, Bashful, Quirky, Serious), which raise/lower the same stat as each
 * other — i.e. no net change — and so carry `raises: null, lowers: null` here.
 */

export type StatName = "attack" | "defense" | "specialAttack" | "specialDefense" | "speed";

export interface NatureDef {
  name: string;
  /** The stat this nature raises by 10%, or null for a neutral nature. */
  raises: StatName | null;
  /** The stat this nature lowers by 10%, or null for a neutral nature. */
  lowers: StatName | null;
}

export const natures: NatureDef[] = [
  { name: "Hardy", raises: null, lowers: null },
  { name: "Lonely", raises: "attack", lowers: "defense" },
  { name: "Brave", raises: "attack", lowers: "speed" },
  { name: "Adamant", raises: "attack", lowers: "specialAttack" },
  { name: "Naughty", raises: "attack", lowers: "specialDefense" },
  { name: "Bold", raises: "defense", lowers: "attack" },
  { name: "Docile", raises: null, lowers: null },
  { name: "Relaxed", raises: "defense", lowers: "speed" },
  { name: "Impish", raises: "defense", lowers: "specialAttack" },
  { name: "Lax", raises: "defense", lowers: "specialDefense" },
  { name: "Timid", raises: "speed", lowers: "attack" },
  { name: "Hasty", raises: "speed", lowers: "defense" },
  { name: "Serious", raises: null, lowers: null },
  { name: "Jolly", raises: "speed", lowers: "specialAttack" },
  { name: "Naive", raises: "speed", lowers: "specialDefense" },
  { name: "Modest", raises: "specialAttack", lowers: "attack" },
  { name: "Mild", raises: "specialAttack", lowers: "defense" },
  { name: "Quiet", raises: "specialAttack", lowers: "speed" },
  { name: "Bashful", raises: null, lowers: null },
  { name: "Rash", raises: "specialAttack", lowers: "specialDefense" },
  { name: "Calm", raises: "specialDefense", lowers: "attack" },
  { name: "Gentle", raises: "specialDefense", lowers: "defense" },
  { name: "Sassy", raises: "specialDefense", lowers: "speed" },
  { name: "Careful", raises: "specialDefense", lowers: "specialAttack" },
  { name: "Quirky", raises: null, lowers: null },
];
